[package]
name = "shade_admin_ensemble"
version = "0.1.0"
authors = ["sbeem <sbeem@pm.me>", "scrtreddev <scrtredev@protonmail.com", "hoomp <flammable.shower939@anonaddy.me>"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
  "cached_contracts",
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]
cosmwasm-std = { package = "secret-cosmwasm-std", version = "0.10.0" }
cosmwasm-storage = { package = "secret-cosmwasm-storage", version = "0.10.0" }
cosmwasm-schema = "0.10.1"

shade_admin = { path = "../shade_admin" }

syn = { version="1.0.57",features=["full","fold"] }
quote = "1.0.8"

fadroma = { branch = "v100", git = "https://github.com/hackbg/fadroma.git" }
