[package]
name = "shade-admin"
version = "0.1.0"
authors = ["sbeem <sbeem@pm.me>", "scrtreddev <scrtredev@protonmail.com", "hoomp <flammable.shower939@anonaddy.me>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
# for quicker tests, cargo test --lib
scrt = ["core"]
# for contracts ( we don't export cosmwasm-std here because it needs to be included as a contract level dependency
# in order for the build to work )
core = ["storage"]
storage = ["shade-protocol/storage_plus"]

[dependencies]
# Core
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", branch = "secret" }
cosmwasm-schema = { git = "https://github.com/CosmWasm/cosmwasm", commit = "1e05e7e" }
schemars = "0.8.9"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0"
shade-protocol = { git = "https://github.com/securesecrets/shade", branch = "cosmwasm_v1_upgrade", features = ["interface", "utils"] }

# https://docs.rs/getrandom/latest/getrandom/#webassembly-support
getrandom = { version = "0.2", features = ["js"] }


