[package]
name = "shade-admin-multi-test"
version = "0.1.0"
authors = ["sbeem <sbeem@pm.me>", "scrtreddev <scrtredev@protonmail.com", "hoomp <flammable.shower939@anonaddy.me>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]
anyhow = "1"
shade-admin = { path = "../shade_admin", features = ["multi-test", "core"] }
admin = { path = "../../contracts/admin" }